[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

[dev]
  framework = "vite"
  command = "npm run dev"
  port = 8888
  targetPort = 5173
  publish = "dist"
  functions = "functions"
